### ISSUE TITLE
Cannot combine Morley and hybridisation for CG

### ISSUE THREAD

**Issue by pefarrell** [firedrakeproject/tsfc#204]
The following code

```
from firedrake import *

def run_morley_hcg(N):
    mesh = UnitSquareMesh(N, N)
    x = SpatialCoordinate(mesh)

    # set up variational problem
    U = FunctionSpace(mesh, "Morley", 2) # change to CG and it compiles
    Ve = FiniteElement("CG", mesh.ufl_cell(), 1)
    Re = FiniteElement("CG" , mesh.ufl_cell(), 1)
    R = FunctionSpace(mesh, Re)
    V = FunctionSpace(mesh, VectorElement(BrokenElement(Ve)))
    Qhat = FunctionSpace(mesh, VectorElement(BrokenElement(Ve[facet])))
    Vhat = FunctionSpace(mesh, VectorElement(Ve[facet]))
    Z  = MixedFunctionSpace([U, V, Qhat, Vhat, R])

    z = Function(Z)
    (u, d, qhat, dhat, lam) = split(z)

    q = Constant(30)
    W = Constant(1)
    a = Constant(-5*2)
    b = Constant(0)
    c = Constant(5*2)
    B = Constant(1e-5)
    K = Constant(0.3)

    s = FacetNormal(mesh)
    trans = as_matrix([[1, 0], [0, 1]])
    mat = trans*grad(grad(u))*trans + q**2 * outer(d, d) * u
    J = (
          + a/2 * u**2 * dx
          + b/3 * u**3 * dx
          + c/4 * u**4 * dx
          + B   * inner(mat, mat) * dx
          + K/2 * inner(grad(d), grad(d)) * dx
          + W/2 * dot(s, d)**2 * ds(1)
          - W/2 * dot(s, d)**2 * ds(2)
        )
    L_match = inner(qhat, dhat - d)
    L = J + inner(lam, inner(d, d)-1) * dx + (L_match('+') + L_match('-'))*dS + L_match*ds

    F = derivative(L, z, TestFunction(Z))
    bcs = None

    # direct solve using LU decomposition
    params = {
        'snes_monitor': None,
        'snes_linesearch_type': 'l2',
        'snes_linesearch_maxstep': 1,
        'snes_linesearch_monitor': None,
        'ksp_type': 'preonly',
        'pc_type': 'lu',
        'pc_factor_mat_solver_type': 'mumps',
        'mat_type': 'aij',
    }

    val = conditional(lt(x[0], 0.5), Constant((-1/sqrt(2), +1/sqrt(2))), Constant((+1/sqrt(2), +1/sqrt(2))))
    z.split()[0].project(Constant(1), solver_parameters=params)
    z.split()[1].interpolate(val)
    z.split()[4].interpolate(Constant(1))

    solve(F == 0, z, bcs, solver_parameters=params)

    u = z.split()[0]
    u = project(u, FunctionSpace(mesh, "DG", 2))
    u.rename("Density")
    d = z.split()[1]
    d.rename("Director")
    File("output/solution_dg.pvd").write(u, d)
    d = project(d, VectorFunctionSpace(mesh, "CG", 1), solver_parameters=params)
    d.rename("Director")
    File("output/solution_cg.pvd").write(u, d)


run_morley_hcg(N=2**5)
```

crashes with

```
Traceback (most recent call last):
  File "/scratch/farrellp/install-scripts/firedrake/firedrake-dev-20190903-mpich/src/PyOP2/pyop2/caching.py", line 197, in __new__
    return cls._cache_lookup(key)
  File "/scratch/farrellp/install-scripts/firedrake/firedrake-dev-20190903-mpich/src/firedrake/firedrake/tsfc_interface.py", line 59, in _cache_lookup
    return cls._cache.get(key) or cls._read_from_disk(key, comm)
  File "/scratch/farrellp/install-scripts/firedrake/firedrake-dev-20190903-mpich/src/firedrake/firedrake/tsfc_interface.py", line 80, in _read_from_disk
    raise KeyError("Object with key %s not found" % key)
KeyError: 'Object with key 0008cba356dd8fe5f872a691c1ab6089 not found'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "hybridisation-experiment.py", line 76, in <module>
    run_morley_hcg(N=2**5)
  File "hybridisation-experiment.py", line 63, in run_morley_hcg
    solve(F == 0, z, bcs, solver_parameters=params)
  File "/scratch/farrellp/install-scripts/firedrake/firedrake-dev-20190903-mpich/src/firedrake/firedrake/adjoint/solving.py", line 48, in wrapper
    output = solve(*args, **kwargs)
  File "/scratch/farrellp/install-scripts/firedrake/firedrake-dev-20190903-mpich/src/firedrake/firedrake/solving.py", line 127, in solve
    _solve_varproblem(*args, **kwargs)
  File "/scratch/farrellp/install-scripts/firedrake/firedrake-dev-20190903-mpich/src/firedrake/firedrake/solving.py", line 170, in _solve_varproblem
    appctx=appctx)
  File "/scratch/farrellp/install-scripts/firedrake/firedrake-dev-20190903-mpich/src/pyadjoint/pyadjoint/tape.py", line 46, in wrapper
    return function(*args, **kwargs)
  File "/scratch/farrellp/install-scripts/firedrake/firedrake-dev-20190903-mpich/src/firedrake/firedrake/adjoint/variational_solver.py", line 24, in wrapper
    init(self, problem, *args, **kwargs)
  File "/scratch/farrellp/install-scripts/firedrake/firedrake-dev-20190903-mpich/src/firedrake/firedrake/variational_solver.py", line 185, in __init__
    options_prefix=self.options_prefix)
  File "/scratch/farrellp/install-scripts/firedrake/firedrake-dev-20190903-mpich/src/firedrake/firedrake/solving_utils.py", line 134, in __init__
    form_compiler_parameters=self.fcp)
  File "/scratch/farrellp/install-scripts/firedrake/firedrake-dev-20190903-mpich/src/firedrake/firedrake/assemble.py", line 164, in create_assembly_callable
    loops = tuple(loops)
  File "/scratch/farrellp/install-scripts/firedrake/firedrake-dev-20190903-mpich/src/firedrake/firedrake/assemble.py", line 237, in _assemble
    kernels = tsfc_interface.compile_form(f, "form", parameters=form_compiler_parameters, inverse=inverse, diagonal=diagonal)
  File "/scratch/farrellp/install-scripts/firedrake/firedrake-dev-20190903-mpich/src/firedrake/firedrake/tsfc_interface.py", line 223, in compile_form
    number_map, interface, coffee, diagonal).kernels
  File "/scratch/farrellp/install-scripts/firedrake/firedrake-dev-20190903-mpich/src/PyOP2/pyop2/caching.py", line 199, in __new__
    obj = make_obj()
  File "/scratch/farrellp/install-scripts/firedrake/firedrake-dev-20190903-mpich/src/PyOP2/pyop2/caching.py", line 189, in make_obj
    obj.__init__(*args, **kwargs)
  File "/scratch/farrellp/install-scripts/firedrake/firedrake-dev-20190903-mpich/src/firedrake/firedrake/tsfc_interface.py", line 128, in __init__
    tree = tsfc_compile_form(form, prefix=name, parameters=parameters, interface=interface, coffee=coffee, diagonal=diagonal)
  File "/scratch/farrellp/install-scripts/firedrake/firedrake-dev-20190903-mpich/src/tsfc/tsfc/driver.py", line 64, in compile_form
    kernel = compile_integral(integral_data, fd, prefix, parameters, interface=interface, coffee=coffee, diagonal=diagonal)
  File "/scratch/farrellp/install-scripts/firedrake/firedrake-dev-20190903-mpich/src/tsfc/tsfc/driver.py", line 207, in compile_integral
    **config)
  File "/scratch/farrellp/install-scripts/firedrake/firedrake-dev-20190903-mpich/src/tsfc/tsfc/fem.py", line 661, in compile_ufl
    result = map_expr_dags(context.translator, expressions)
  File "/scratch/farrellp/install-scripts/firedrake/firedrake-dev-20190903-mpich/src/ufl/ufl/corealg/map_dag.py", line 84, in map_expr_dags
    r = handlers[v._ufl_typecode_](v)
  File "/scratch/farrellp/install-scripts/firedrake/firedrake-dev-20190903-mpich/src/tsfc/tsfc/ufl_utils.py", line 144, in _modified_terminal
    return self.modified_terminal(o)
  File "/scratch/farrellp/install-scripts/firedrake/firedrake-dev-20190903-mpich/src/tsfc/tsfc/fem.py", line 319, in modified_terminal
    return translate(mt.terminal, mt, self.context)
  File "/usr/lib/python3.6/functools.py", line 807, in wrapper
    return dispatch(args[0].__class__)(*args, **kw)
  File "/scratch/farrellp/install-scripts/firedrake/firedrake-dev-20190903-mpich/src/tsfc/tsfc/fem.py", line 597, in translate_coefficient
    finat_dict = ctx.basis_evaluation(element, mt, entity_id)
  File "/scratch/farrellp/install-scripts/firedrake/firedrake-dev-20190903-mpich/src/tsfc/tsfc/fem.py", line 244, in basis_evaluation
    coordinate_mapping=CoordinateMapping(mt, self))
  File "/scratch/farrellp/install-scripts/firedrake/firedrake-dev-20190903-mpich/src/FInAT/finat/physically_mapped.py", line 95, in basis_evaluation
    M = self.basis_transformation(coordinate_mapping)
  File "/scratch/farrellp/install-scripts/firedrake/firedrake-dev-20190903-mpich/src/FInAT/finat/morley.py", line 45, in basis_transformation
    h = coordinate_mapping.cell_size()
  File "/scratch/farrellp/install-scripts/firedrake/firedrake-dev-20190903-mpich/src/tsfc/tsfc/fem.py", line 138, in cell_size
    return self.interface.cell_size(self.mt.restriction)
  File "/scratch/farrellp/install-scripts/firedrake/firedrake-dev-20190903-mpich/src/tsfc/tsfc/kernel_interface/common.py", line 67, in cell_size
    return gem.partial_indexed(self._cell_sizes, f)
  File "/scratch/farrellp/install-scripts/firedrake/firedrake-dev-20190903-mpich/src/tsfc/gem/gem.py", line 814, in partial_indexed
    elif len(indices) < len(tensor.shape):
AttributeError: 'tuple' object has no attribute 'shape'
```

If I change `"Morley"` to `"CG"`, it compiles (although the PDE doesn't make sense).

**Comment by rckirby** [comment]
does this happen with other zany elements (Bell or Argyris) or just Morley?

**Comment by pefarrell** [comment]
I get the same problem with Bell and Argyris.

**Comment by rckirby** [comment]
ok, Could be something in the physicallymapped hierarchy that overrides something incorrectly in the fiat hierarchy?
